# Site
name: "홍익과학기술 블로그"
title: "홍익과학기술"
description: "클라우드 및 인프라 관리 진행해요!, dnd, d&d"
site_description: "홍익과학기술 기술 블로그!!"
logo: "assets/images/hongikit/logo.png"
favicon: "assets/images/hongikit/logo.png"
og_image: "assets/images/hongikit/hongikit_login.jpg"
google_analytics: "UA-167083100-1"
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/
email: mts201224@gmail.com

# Authors
authors:
  Sungbin:
    name: 한성빈
    display_name: 한성빈
    gravatar: sb.png
    email: cloud.seongbin@gmail.com
    web: https://github.com/HanSeongbin
  Gidong:
    name: 성기동
    display_name: 성기동
    gravatar: SeongGiDong.png
    email: sgd0947@gmail.com
    web: https://github.com/sgd122/
  MyeongHan:
    name: 김명한
    display_name: 김명한
    gravatar: kmh.png
    email: dbwmflgk12@naver.com

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
